name: NASA Project CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        env:
            CI: true
        strategy:
            matrix:
                node-version: [16.x, 20.x]
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js version ${{ matrix.node-varsion }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm run install-all
            - run: npm run build --prefix client
            - run: npm test
